on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test GH action
        id: zeonSetup
        uses: ./

      - name: Get the output time
        run: echo "Status;  ${{ steps.zeonSetup.outputs.ok }}"
