on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Test GH action
        id: zeonSetup
        uses: ./

      - name: Get the output time
        run: echo "The time was ${{ steps.zeonSetup.outputs.time }}"
